import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import {
  mkdir,
  mkdtemp,
  readFile,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Writable } from "node:stream";
import test from "node:test";
import { promisify } from "node:util";
import type {
  MigrationSummary,
  ValidationResult,
} from "@codeshift/shared";
import {
  buildPullRequestBody,
  createBranchName,
  createGitHubPullRequest,
  parseGitHubRemote,
  runGitHubPRFlow,
  type PRPrompter,
} from "./github-pr.js";

const execFileAsync = promisify(execFile);

test("creates deterministic branch names and parses github.com remotes", () => {
  assert.equal(
    createBranchName(new Date("2026-07-03T12:34:56.000Z")),
    "codeshift-ai/js-to-ts-20260703-123456",
  );
  assert.deepEqual(
    parseGitHubRemote("https://github.com/acme/legacy-api.git"),
    { owner: "acme", repo: "legacy-api" },
  );
  assert.deepEqual(
    parseGitHubRemote("git@github.com:acme/legacy-api.git"),
    { owner: "acme", repo: "legacy-api" },
  );
  assert.equal(
    parseGitHubRemote("https://gitlab.com/acme/legacy-api.git"),
    null,
  );
  assert.equal(
    parseGitHubRemote("http://github.com/acme/legacy-api.git"),
    null,
  );
  assert.equal(
    parseGitHubRemote("https://token@github.com/acme/legacy-api.git"),
    null,
  );
});

test("builds a professional pull request body from migration artifacts", () => {
  const body = buildPullRequestBody({
    migration: createMigrationSummary(),
    validationResults: createValidationResults(),
  });

  assert.match(body, /^## Summary/m);
  assert.match(body, /^## Files Changed/m);
  assert.match(body, /^## Validation/m);
  assert.match(body, /- test: PASSED/);
  assert.match(body, /- lint: SKIPPED/);
  assert.match(body, /^## Warnings \/ Risk Notes/m);
  assert.match(body, /Dynamic require detected/);
  assert.match(body, /Generated by CodeShift AI/);
});

test("creates a GitHub pull request with the expected authenticated request", async () => {
  let requestedURL = "";
  let requestedInit: RequestInit | undefined;
  const fakeFetch = (async (
    input: string | URL | Request,
    init?: RequestInit,
  ) => {
    requestedURL = String(input);
    requestedInit = init;
    return new Response(
      JSON.stringify({
        html_url: "https://github.com/acme/legacy-api/pull/42",
      }),
      {
        status: 201,
        headers: { "Content-Type": "application/json" },
      },
    );
  }) as typeof fetch;

  const url = await createGitHubPullRequest({
    repository: { owner: "acme", repo: "legacy-api" },
    token: "test-token",
    title: "Migrate src/utils from JavaScript to TypeScript",
    body: "Review me",
    head: "codeshift-ai/js-to-ts-20260703-123456",
    base: "main",
    fetchImplementation: fakeFetch,
  });

  assert.equal(url, "https://github.com/acme/legacy-api/pull/42");
  assert.equal(
    requestedURL,
    "https://api.github.com/repos/acme/legacy-api/pulls",
  );
  assert.equal(requestedInit?.method, "POST");
  const headers = new Headers(requestedInit?.headers);
  assert.equal(headers.get("Authorization"), "Bearer test-token");
  assert.equal(headers.get("X-GitHub-Api-Version"), "2026-03-10");
  assert.deepEqual(JSON.parse(String(requestedInit?.body)), {
    title: "Migrate src/utils from JavaScript to TypeScript",
    body: "Review me",
    head: "codeshift-ai/js-to-ts-20260703-123456",
    base: "main",
  });
});

test("creates only an approved local branch and scoped commit when no token is provided", async () => {
  const root = await createGitFixture();
  let output = "";
  const confirmations: string[] = [];
  const prompter: PRPrompter = {
    async confirm(message) {
      confirmations.push(message);
      return true;
    },
    async requestToken() {
      return "";
    },
  };
  const stream = new Writable({
    write(chunk, _encoding, callback) {
      output += chunk.toString();
      callback();
    },
  });

  try {
    const result = await runGitHubPRFlow({
      cwd: root,
      environment: {},
      now: new Date("2026-07-03T12:34:56.000Z"),
      output: stream,
      prompter,
    });

    assert.deepEqual(result, {
      status: "LOCAL_COMMIT_CREATED",
      branchName: "codeshift-ai/js-to-ts-20260703-123456",
    });
    assert.equal(confirmations.length, 2);
    assert.match(confirmations[0] ?? "", /Create branch/);
    assert.match(confirmations[1] ?? "", /Stage only the migration files/);
    assert.equal(await git(root, ["branch", "--show-current"]), result.branchName);
    assert.equal(
      await git(root, ["log", "-1", "--pretty=%s"]),
      "Migrate src/utils from JavaScript to TypeScript",
    );

    const committedFiles = (
      await git(root, ["show", "--pretty=", "--name-only", "HEAD"])
    )
      .split(/\r?\n/)
      .filter(Boolean);
    assert.deepEqual(committedFiles.sort(), [
      "src/utils/math.js",
      "src/utils/math.ts",
      "tsconfig.json",
    ]);
    assert.match(await git(root, ["status", "--short"]), /\?\? notes\.txt/);
    assert.match(output, /Validation:/);
    assert.match(output, /Local branch and commit are ready/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("does not mutate Git state when branch creation is declined", async () => {
  const root = await createGitFixture();
  const prompter: PRPrompter = {
    async confirm() {
      return false;
    },
    async requestToken() {
      assert.fail("A token should not be requested after cancellation.");
    },
  };

  try {
    const beforeCommit = await git(root, ["rev-parse", "HEAD"]);
    const result = await runGitHubPRFlow({
      cwd: root,
      environment: {},
      now: new Date("2026-07-03T12:34:56.000Z"),
      output: new Writable({
        write(_chunk, _encoding, callback) {
          callback();
        },
      }),
      prompter,
    });

    assert.equal(result.status, "CANCELLED");
    assert.equal(await git(root, ["branch", "--show-current"]), "main");
    assert.equal(await git(root, ["rev-parse", "HEAD"]), beforeCommit);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

async function createGitFixture(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "codeshift-pr-"));
  await git(root, ["init", "--initial-branch=main"]);
  await git(root, ["config", "user.name", "CodeShift AI Test"]);
  await git(root, ["config", "user.email", "codeshift-ai@example.test"]);
  await mkdir(join(root, "src", "utils"), { recursive: true });
  await writeFile(join(root, ".gitignore"), ".codeshift-ai/\n", "utf8");
  await writeFile(
    join(root, "src", "utils", "math.js"),
    "module.exports = function add(a, b) { return a + b; };\n",
    "utf8",
  );
  await git(root, ["add", "."]);
  await git(root, ["commit", "-m", "Initial fixture"]);
  await git(root, [
    "remote",
    "add",
    "origin",
    "https://github.com/acme/legacy-api.git",
  ]);

  await rename(
    join(root, "src", "utils", "math.js"),
    join(root, "src", "utils", "math.ts"),
  );
  await writeFile(
    join(root, "src", "utils", "math.ts"),
    "export default function add(a, b) { return a + b; }\n",
    "utf8",
  );
  await writeFile(
    join(root, "tsconfig.json"),
    JSON.stringify({ compilerOptions: { noEmit: true } }, null, 2) + "\n",
    "utf8",
  );
  await writeFile(join(root, "notes.txt"), "unrelated change\n", "utf8");

  await mkdir(join(root, ".codeshift-ai"), { recursive: true });
  await writeFile(
    join(root, ".codeshift-ai", "migration-summary.json"),
    JSON.stringify(createMigrationSummary(), null, 2),
    "utf8",
  );
  await writeFile(
    join(root, ".codeshift-ai", "validation-result.json"),
    JSON.stringify(createValidationResults(), null, 2),
    "utf8",
  );
  await writeFile(
    join(root, ".codeshift-ai", "patch.diff"),
    [
      "similarity index 71%",
      "rename from src/utils/math.js",
      "rename to src/utils/math.ts",
      "",
    ].join("\n"),
    "utf8",
  );

  return root;
}

function createMigrationSummary(): MigrationSummary {
  return {
    target: "JS_TO_TS",
    selectedScope: "src/utils",
    changedFiles: ["src/utils/math.ts", "tsconfig.json"],
    warnings: ["Dynamic require detected in one file and left unchanged"],
    tsconfigChanged: true,
    createdAt: "2026-07-03T12:00:00.000Z",
  };
}

function createValidationResults(): ValidationResult[] {
  return [
    {
      command: "npm run test",
      status: "PASSED",
      logs: "Tests passed",
      durationMs: 120,
    },
    {
      command: "npm run lint",
      status: "SKIPPED",
      logs: "Script not defined",
    },
  ];
}

async function git(root: string, args: string[]): Promise<string> {
  const result = await execFileAsync("git", args, {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
  });
  return result.stdout.trim();
}
